name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
    
    - name: Ensure SRC
      run: mkdir -p /home/runner/work/workspace/src/github.com/toorosan
    
    - name: Copy SRC
      run: ln -s /home/runner/work/rss/rss /home/runner/go/src/github.com/toorosan/
    
    #- name: Switch current dir
    #  run: cd /home/runner/go/src/github.com/toorosan/rss

    - name: Install
      run: GOPATH=/home/runner/work/workspace go install -race -v ./...
#       env:
#         GOPATH: /home/runner/go

    - name: Test
      run: GOPATH=/home/runner/work/workspace go test -json ./...
