name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
    
    - name: Ensure SRC
      run: mkdir -p $GOPATH/src/github.com/toorosan

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        path: $GOPATH/src/github.com/toorosan/rss
    
    - name: Switch current dir
      run: cd $GOPATH/src/github.com/toorosan/rss

    - name: Install
      run: go install -race -v ./...

    - name: Test
      run: go test -json ./...
